# Generated by Django 3.2.16 on 2023-02-13 11:02

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantes',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='integrantes', variations={}, verbose_name='foto'),
        ),
    ]
