# Generated by Django 3.2.16 on 2023-02-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='area',
            field=models.CharField(choices=[('Aerodinâmica', 'Aerodinâmica'), ('Direção', 'Direção e Suspenção'), ('Elétrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('NA', 'Nenhuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='integrantes',
            name='area',
            field=models.CharField(choices=[('Aerodinâmica', 'Aerodinâmica'), ('Direção', 'Direção e Suspenção'), ('Elétrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('NA', 'Nenhuma')], max_length=50),
        ),
        migrations.AlterField(
            model_name='objetivosarea',
            name='area',
            field=models.CharField(choices=[('Aerodinâmica', 'Aerodinâmica'), ('Direção', 'Direção e Suspenção'), ('Elétrica', 'Elétrica'), ('Estrutura', 'Estrutura'), ('Freio e Ergonomia', 'Freio e Ergonomia'), ('Powewtrain', 'Powewtrain'), ('Comercial', 'Comercial'), ('Financeiro', 'Financeiro'), ('Gestão', 'Gestão de Pessoas'), ('Marketing', 'Marketing'), ('NA', 'Nenhuma')], default='Nenhuma', max_length=50),
        ),
    ]
